import torch

DINPUT = 4
DSTATE = DINPUT
DMLP1 = 64
DMLP2 = 64
EPS = 1e-8
SEED = 42
BATCH_SIZE = 8192
NUM_BATCHES = 16
SAMPLES = BATCH_SIZE * NUM_BATCHES
VAL_SAMPLES = BATCH_SIZE * 4
SEQ_LEN = 4
VAL_SEQ_LEN = 16
LR = 1e-3
WD = 1e-1
EPOCHS = 2000
LAMBDA = 1
RNN_TRAJ_STEPS = 2
SLERP_TRAJ_STEPS = 20
DEVICETYPE = "cuda" if torch.cuda.is_available() else "cpu"
DEVICE = torch.device(DEVICETYPE)